/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectanggota.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import projectanggota.model.Anggota;

/**
 *
 * @author PKane_NS
 */
public class KepoDialog extends javax.swing.JDialog {

    /**
     * Creates new form KepoDialog
     */
    public KepoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTable();
    }
    DefaultTableModel tableModel;
    Object[] column = {"ID", "Nama", "NIM"};
    void setTable(){
        tableModel = new DefaultTableModel(column, 0);
        tableKepo.setModel(tableModel);
    }   
    public KepoDialog(){
        initComponents();
        setTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableKepo = new javax.swing.JTable();
        bKepo = new javax.swing.JButton();
        tfKepo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableKepo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableKepo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 340, 220));

        bKepo.setText("Cari");
        bKepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKepoActionPerformed(evt);
            }
        });
        getContentPane().add(bKepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));
        getContentPane().add(tfKepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, -1));

        jLabel1.setText("input kepo mu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bKepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKepoActionPerformed
        try {
            String kepo = tfKepo.getText();
            List<Anggota> anggotas = home.client.getAnggotasByKepo(kepo);
            Object[][] data = new Object[anggotas.size()][3];
            int i=0;
            for(Anggota a: anggotas){
                Object[] arr_data = {a.getId(), a.getNama(), a.getNim()};
                data[i] = arr_data;
                i++;
            }
            tableModel = new DefaultTableModel(data, column);
            tableKepo.setModel(tableModel);
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bKepoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KepoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KepoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KepoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KepoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KepoDialog dialog = new KepoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKepo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKepo;
    private javax.swing.JTextField tfKepo;
    // End of variables declaration//GEN-END:variables
}
